default_provider = "ingot-crypto"

[providers.ingot-crypto]
type = "age"
recipients = ["age1ldm5xzq85pu7d4xg3spehhgt4ej57pcn0usqrpfe9nu8fc8edphq3md5c6"]

[secrets]
MY_SECRET= { provider = "ingot-crypto", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsSnlvREVVelkyVC9vTndjSFlSTk9tT2pwMXJWMUw3SERWZWVLL0h6cmxjCnJmU1VuQmF6SHdjNDk5eHRhbXdrTXpMcmNZcVIvM3J3dE1hMkJiMXVzRFUKLT4gUDhwWkMtZ3JlYXNlIEd+XTVpVSBNOiRQJTAqJApBZlloWWdnZjVVa2UxVkQ4dXN1WUVoc0FUNk0rblZpSVp1c2lmbHMrc2VKSWpSSm1XdVlpZ0U2ODBXcVh5dU44Ck1WeEdyVysvMGpoZmdIM2UyOGVPaDNnSVBBCi0tLSA3cGV3dXB6angzS2pMUm8reko5N0w5WDI3eW95MGhPZ0tkSDc1RUFVSmlRCv45DURq1whoy1r7WzbhWdcfJCs9IGCKMcC3nxTd+FWGdLKe0qBAjTpPg1OeS4cYssFG" }
